import React, { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import ExperienceInfo from "../components/ExperienceInfo/ExperienceInfo";
import EducationInfo from "../components/EducationInfo/EducationInfo";
import Header from "../components/Header/Header";
import Layout from "../components/Layout/Layout";
import Image from "next/image";

const About: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>About | Nam</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          ></meta>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header></Header>

        <div className={styles.main}>
          <h1 className={styles.title}>About Nam</h1>
        </div>

        <a href="#top">Back to top</a>
        <hr style={{ width: "100%" }}></hr>
        <footer className={styles.footer}>Copyright © Nam</footer>
      </div>
    </Layout>
  );
};

export default About;
