import React, { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import ExperienceInfo from "../components/ExperienceInfo/ExperienceInfo";
import EducationInfo from "../components/EducationInfo/EducationInfo";
import Header from "../components/Header/Header";
import Layout from "../components/Layout/Layout";
import Image from "next/image";
import about from "../public/images/about.jpg";
import icandoit from "../public/images/icandoit.jpg";
const About: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>About | Nhi</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          ></meta>
          <link rel="preconnect" href="https://fonts.googleapis.com"></link>
          <link rel="preconnect" href="https://fonts.gstatic.com"></link>
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header></Header>

        <div className={styles.main}>
          <h1 className={styles.title}>About me</h1>
          <div className={styles.illustrations}>
            <Image src={about} width={175} height={175} alt={"Illustration"} />
          </div>
          <p className={styles.description}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </p>
        </div>

        <div className={styles.main}>
          <h1 className={styles.title}>Experience</h1>

          <div className={styles.parallel}>
            <div className={styles.illustrations}>
              <Image
                src={icandoit}
                width={175}
                height={175}
                alt={"Illustration"}
              />
            </div>
            <ExperienceInfo></ExperienceInfo>
          </div>
        </div>

        <div className={styles.main}>
          <h1 className={styles.title}>Journey</h1>
          <div className={styles.illustrations}>
            <Image
              src={icandoit}
              width={175}
              height={175}
              alt={"Illustration"}
            />
          </div>

          <p className={styles.description}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </p>
          <div className={styles.illustrations}>
            <Image
              src={icandoit}
              width={175}
              height={175}
              alt={"Illustration"}
            />
          </div>

          <p className={styles.description}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </p>
          <div className={styles.illustrations}>
            <Image
              src={icandoit}
              width={175}
              height={175}
              alt={"Illustration"}
            />
          </div>
          <p className={styles.description}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </p>
          <div className={styles.illustrations}>
            <Image
              src={icandoit}
              width={175}
              height={175}
              alt={"Illustration"}
            />
          </div>
          <p className={styles.description}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </p>
          <div className={styles.illustrations}>
            <Image
              src={icandoit}
              width={175}
              height={175}
              alt={"Illustration"}
            />
          </div>
        </div>

        <a href="#top">Back to top</a>
        <hr style={{ width: "100%" }}></hr>
        <footer className={styles.footer}>Copyright © Nam</footer>
      </div>
    </Layout>
  );
};

export default About;
