import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Layout from "../components/Layout/Layout";
import hi from "../public/images/hi.jpg";
const Home: NextPage = () => {
  return (
    <Layout>
      <div className={styles.page}>
        <Head>
          <title>Home | Nhi Luu</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          ></meta>
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <p className={styles.welcomeText}>
            Hello, my name is Nhi. Welcome to my website !
          </p>

          <div className={styles.illustrations}>
            <Image src={hi} width={250} height={250} alt={"Illustration"} />
          </div>

          <div className={styles.wrapper}>
            <Link href="/about" passHref>
              <div className={styles.card}>
                <h2>About</h2>
              </div>
            </Link>

            <Link href="/now" passHref>
              <div className={styles.card}>
                <h2>Now</h2>
              </div>
            </Link>
          </div>
        </main>
      </div>
    </Layout>
  );
};

export default Home;
