import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import Image from "next/image";

import Layout from "../components/Layout/Layout";

const Now: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Now | Nam</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          ></meta>
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.main}>
          <Header></Header>
          <h1 className={styles.title}>What I am up to</h1>
          <ul className={styles.description}>
            <li>Currently in Silver Spring, MD, US</li>
          </ul>

          <p className={styles.description}>
            Find me at <a href="https://github.com/ttran293">GitHub   </a>
            <a href="https://www.linkedin.com/in/thanh-nam-tran-9bbb921b3/">
               LinkedIn
            </a>
          </p>
        </div>
        <hr style={{ width: "100%" }}></hr>
        <footer className={styles.footer}>Copyright © Nam</footer>
      </div>
    </Layout>
  );
};

export default Now;
